# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wP6k35Z_GzWD3M063SF7qrB6ESdLIlb
"""

pip install pandas scikit-learn matplotlib seaborn joblib

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

from sklearn.calibration import CalibratedClassifierCV
from sklearn.utils.class_weight import compute_sample_weight

from xgboost import XGBClassifier

print("Libraries Imported Successfully!")

from google.colab import files
import pandas as pd

# Upload file from desktop
uploaded = files.upload()

# Get filename
file_name = list(uploaded.keys())[0]

# Read JSON dataset
df = pd.read_json(file_name)

print("JSON Dataset Loaded Successfully!")

print(df.head())

print(df.columns)

df = df.dropna()

print("Missing Values Removed!")

# CHANGE COLUMN NAMES IF NEEDED

X = df['code']
y = df['labels']

y = y.apply(
    lambda x: x[0] if isinstance(x, list) else x
)

print(y.head())

label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Labels Encoded Successfully!")

# ============================================================
# REMOVE UNWANTED SMELLS
# ============================================================

remove_classes = [

    'TensorArray Not Used',

    'Broadcasting Feature Not Used',

    'Empty Column Misinitialization',

    'Columns and DataType Not Explicitly Set',

    'Deterministic Algorithm Option Not Used'

]

# Remove rows containing these smells
df = df[
    ~df['label'].isin(remove_classes)
]

print("\nRemaining Classes:\n")

print(df['label'].value_counts())

y = y.apply(
    lambda x: x[0] if isinstance(x, list) else x
)

# Create temporary dataframe
temp_df = df.copy()

temp_df['label'] = y

# Separate No Smell
no_smell_df = df[
    df['label'] == 'No Smell'
]

# Separate all other smells
other_df = df[
    df['label'] != 'No Smell'
]

print("Original No Smell Count:",
      len(no_smell_df))

# Keep only 4000 samples
no_smell_df = no_smell_df.sample(
    n=4000,
    random_state=42
)

print("Reduced No Smell Count:",
      len(no_smell_df))

# Combine datasets
df = pd.concat(
    [no_smell_df, other_df],
    ignore_index=True
)

# Shuffle dataset
df = df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("\nFINAL DATASET DISTRIBUTION:\n")

print(df['label'].value_counts())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print("Train Test Split Completed!")

vectorizer = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2)
)

X_train_vectorized = vectorizer.fit_transform(X_train)

X_test_vectorized = vectorizer.transform(X_test)

print("Vectorization Completed!")

sample_weights = compute_sample_weight(
    class_weight='balanced',
    y=y_train
)

print("Class Weights Computed!")

base_model = XGBClassifier(
    n_estimators=100,
    max_depth=4,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=3,
    objective='multi:softprob',
    eval_metric='mlogloss',
    random_state=42,
    verbosity=1
)

print("XGBoost Model Created!")

model = CalibratedClassifierCV(
    base_model,
    method='sigmoid',
    cv=2
)

print("Calibration Added!")

sample_weights = compute_sample_weight(
    class_weight='balanced',
    y=y_train
)

# Convert to float32
sample_weights = sample_weights.astype(np.float32)

print("Class Weights Computed!")

import time

print("\nTraining Started...")

start_time = time.time()

model.fit(
    X_train_vectorized,
    y_train,
    sample_weight=sample_weights
)

end_time = time.time()

total_time = end_time - start_time

print("\nTraining Completed!")

print(f"\nTotal Training Time: {total_time:.2f} seconds")

print(f"Total Training Time: {total_time/60:.2f} minutes")

print("\nPrediction Started...")

prediction_start = time.time()
y_pred = model.predict(X_test_vectorized)
prediction_end = time.time()
prediction_time = prediction_end - prediction_start
print("\nPrediction Completed!")
print(f"\nPrediction Time: {prediction_time:.2f} seconds")

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    average='weighted'
)

recall = recall_score(
    y_test,
    y_pred,
    average='weighted'
)

f1 = f1_score(
    y_test,
    y_pred,
    average='weighted'
)

print("\n==============================")
print("MODEL PERFORMANCE")
print("==============================")

print(f"Accuracy  : {accuracy*100:.2f}%")
print(f"Precision : {precision*100:.2f}%")
print(f"Recall    : {recall*100:.2f}%")
print(f"F1 Score  : {f1*100:.2f}%")

print("\nClassification Report:\n")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=label_encoder.classes_
    )
)

joblib.dump(model, "code_smell_model.pkl")

joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

joblib.dump(label_encoder, "label_encoder.pkl")

print("Model Saved Successfully!")

# ============================================================
# COMPLETE UNSEEN CODE PREDICTION SECTION
# ============================================================

import joblib
import numpy as np


# ============================================================
# 1. LOAD SAVED MODEL
# ============================================================

loaded_model = joblib.load("code_smell_model.pkl")

loaded_vectorizer = joblib.load("tfidf_vectorizer.pkl")

loaded_label_encoder = joblib.load("label_encoder.pkl")

print("Saved Model Loaded Successfully!")


# ============================================================
# 2. REAL CODE SMELL EXAMPLES
# ============================================================

multiple_codes = [

# ------------------------------------------------------------
# CHAIN INDEXING
# ------------------------------------------------------------

"""
import pandas as pd

df['Marks'][0] = 100
""",


# ------------------------------------------------------------
# GRADIENTS NOT CLEARED BEFORE BACKWARD PROPAGATION
# ------------------------------------------------------------

"""
import torch

loss.backward()

optimizer.step()
""",


# ------------------------------------------------------------
# IN-PLACE APIs MISUSED
# ------------------------------------------------------------

"""
import torch

x.relu_()
""",


# ------------------------------------------------------------
# HYPERPARAMETER NOT EXPLICITLY SET
# ------------------------------------------------------------

"""
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train,y_train)
""",


# ------------------------------------------------------------
# NO SMELL
# ------------------------------------------------------------

"""
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train,y_train)
"""


]


# ============================================================
# 3. PREDICT EACH CODE
# ============================================================

for i, code in enumerate(multiple_codes):

    print("\n===================================================")
    print(f"CODE SAMPLE {i+1}")
    print("===================================================")

    print("\nCODE:\n")

    print(code)

    # ========================================================
    # VECTORIZE CODE
    # ========================================================

    vectorized_code = loaded_vectorizer.transform([code])

    vectorized_code = vectorized_code.astype(np.float32)

    # ========================================================
    # PREDICT
    # ========================================================

    prediction = loaded_model.predict(vectorized_code)

    predicted_label = loaded_label_encoder.inverse_transform(
        prediction
    )

    print("\nPREDICTED CODE SMELL:\n")

    print(predicted_label[0])

    # ========================================================
    # PROBABILITIES
    # ========================================================

    probabilities = loaded_model.predict_proba(
        vectorized_code
    )

    top_indices = np.argsort(
        probabilities[0]
    )[::-1][:5]

    print("\nTOP PREDICTIONS:\n")

    for idx in top_indices:

        label = loaded_label_encoder.inverse_transform(
            [idx]
        )[0]

        prob = probabilities[0][idx] * 100

        print(f"{label} : {prob:.2f}%")

    print("\n")

# ============================================================
# COMPLETE CODE SMELL PREDICTION PROGRAM
# ============================================================

# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import joblib
import numpy as np


# ============================================================
# 2. LOAD SAVED MODEL FILES
# ============================================================

loaded_model = joblib.load("code_smell_model.pkl")

loaded_vectorizer = joblib.load("tfidf_vectorizer.pkl")

loaded_label_encoder = joblib.load("label_encoder.pkl")

print("Saved Model Loaded Successfully!")


# ============================================================
# 3. REAL CODE SMELL EXAMPLES
# ============================================================

multiple_codes = [

# ============================================================
# CHAIN INDEXING
# ============================================================

"""
import pandas as pd

df['Marks'][0] = 100
""",


"""
df['Age'][5] = 30
""",


"""
data['Salary'][2] = 50000
""",


# ============================================================
# GRADIENTS NOT CLEARED
# ============================================================

"""
import torch

loss.backward()

optimizer.step()
""",


"""
for batch in loader:

    output = model(batch)

    loss = criterion(output, target)

    loss.backward()

    optimizer.step()
""",


# ============================================================
# IN-PLACE APIS MISUSED
# ============================================================

"""
x.relu_()
""",


"""
tensor.zero_()
""",


"""
weights.add_(5)
""",


# ============================================================
# HYPERPARAMETER NOT EXPLICITLY SET
# ============================================================

"""
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train,y_train)
""",


"""
from sklearn.svm import SVC

clf = SVC()
""",


"""
from xgboost import XGBClassifier

model = XGBClassifier()
""",


# ============================================================
# DATA LEAKAGE
# ============================================================

"""
scaler.fit(X)

X_train, X_test = train_test_split(X)
""",


"""
model.fit(X_test,y_test)
""",


# ============================================================
# RANDOMNESS NOT CONTROLLED
# ============================================================

"""
train_test_split(X,y)
""",


"""
RandomForestClassifier()
""",


# ============================================================
# UNUSED VARIABLES
# ============================================================

"""
temp = model.predict(X)

print("Training Done")
""",


"""
unused_value = 100
""",


# ============================================================
# LONG METHOD
# ============================================================

"""
def process():

    step1()

    step2()

    step3()

    step4()

    step5()

    step6()

    step7()

    step8()

    step9()

    step10()
""",


# ============================================================
# DUPLICATE CODE
# ============================================================

"""
for i in range(10):

    print(i)

for i in range(10):

    print(i)
""",


# ============================================================
# NO SMELL
# ============================================================

"""
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train,y_train)
""",


"""
optimizer.zero_grad()

loss.backward()

optimizer.step()
""",


"""
df.loc[0,'Marks'] = 100
"""

]


# ============================================================
# 4. ACTUAL EXPECTED SMELLS
# ============================================================

actual_smells = [

"Chain Indexing",
"Chain Indexing",
"Chain Indexing",

"Gradients Not Cleared",
"Gradients Not Cleared",

"In-Place APIs Misused",
"In-Place APIs Misused",
"In-Place APIs Misused",

"Hyperparameter Not Explicitly Set",
"Hyperparameter Not Explicitly Set",
"Hyperparameter Not Explicitly Set",

"Data Leakage",
"Data Leakage",

"Randomness Not Controlled",
"Randomness Not Controlled",

"Unused Variable",
"Unused Variable",

"Long Method",

"Duplicate Code",

"No Smell",
"No Smell",
"No Smell"
]


# ============================================================
# 5. PREDICT EACH CODE
# ============================================================

for i, code in enumerate(multiple_codes):

    print("\n===================================================")
    print(f"CODE SAMPLE {i+1}")
    print("===================================================")

    print("\nCODE:\n")

    print(code)

    print("\nEXPECTED SMELL:\n")

    print(actual_smells[i])

    # ========================================================
    # VECTORIZE CODE
    # ========================================================

    vectorized_code = loaded_vectorizer.transform([code])

    vectorized_code = vectorized_code.astype(np.float32)

    # ========================================================
    # PREDICT
    # ========================================================

    prediction = loaded_model.predict(vectorized_code)

    predicted_label = loaded_label_encoder.inverse_transform(
        prediction
    )

    print("\nPREDICTED SMELL:\n")

    print(predicted_label[0])

    # ========================================================
    # PROBABILITIES
    # ========================================================

    probabilities = loaded_model.predict_proba(
        vectorized_code
    )

    top_indices = np.argsort(
        probabilities[0]
    )[::-1][:5]

    print("\nTOP PREDICTIONS:\n")

    for idx in top_indices:

        label = loaded_label_encoder.inverse_transform(
            [idx]
        )[0]

        prob = probabilities[0][idx] * 100

        print(f"{label} : {prob:.2f}%")

    print("\n")